openapi: 3.0.0
servers:
  - description: mapadmin
    url: 'http://localhost:3000/api'
info:
  description: |-
    Все запросы кроме getAuthData, возвращают стандартный ответ вида
    {
      "isError":boolean,
      "response": string or object or array
    },
    В случае ошибки isError будет true, в response будет описание ошибки. Соответственно, в случае успеха isError будет false
  version: 1.0.0
  title: mapadmin API
  contact: {}
  license: {}
tags:
  - name: Авторизация
    description: Интерфейс авторизации
  - name: admin
    description: Интерфейс администратора
  - name: moder
    description: Интерфейс модератора
  - name: user
    description: Интерфейс пользователя
paths:
  /login:
    post:
      tags:
        - Авторизация
      summary: Запрос авторизации
      operationId: login
      requestBody:
        description: |
          Отправляем данные для авторизации
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - login
                - password
              properties:
                login:
                  type: string
                  format: email
                  maxLength: 320
                password:
                  type: string
                  minimum: 8
                  maximum: 72
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    type: string
                required:
                  - isError
                  - response
              examples:
                Успешный вход:
                  value:
                    isError: false
                    response: OK
                Неверный логин или пароль:
                  value:
                    isError: true
                    response: Unauthorized
        '400':
          description: Если какой то параметр не будет отправлен
          content:
            application/json:
              schema:
                type: string
                example: Bad Request
      description: Вход в аккаунт
  /logout:
    post:
      tags:
        - Авторизация
      summary: Выход из аккаунта
      operationId: logout
      description: |
        Выход из аккаунта
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    type: string
                required:
                  - isError
                  - response
              examples:
                Успешный выход:
                  value:
                    isError: false
                    response: OK
                Не авторизован:
                  value:
                    isError: true
                    response: Unauthorized
  /getAuthData:
    get:
      tags:
        - Авторизация
      summary: Получение данных авторизации
      operationId: getAuthData
      description: |
        Получение информации о текущем авторизованном пользователе
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  login:
                    type: string
                  isAuth:
                    type: boolean
                  permission:
                    type: string
                required:
                  - login
                  - isAuth
                  - permission
              examples:
                Авторизация выполнена:
                  value:
                    login: user@user.user
                    isAuth: true
                    permission: user
                Не авторизован:
                  value:
                    login: null
                    isAuth: false
                    permission: null
  /admin/addUser:
    post:
      tags:
        - admin
      summary: Добовление пользователей
      operationId: addUser
      description: |
        Добавление пользователей с различными правами
      requestBody:
        description: |
          Отправляем логин, пароль и id прав
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  maximum: 320
                password:
                  type: string
                  minimum: 8
                  maximum: 72
                permission_id:
                  type: integer
              required:
                - email
                - password
                - permission_id
      responses:
        '200':
          description: Возвращает данные добавленного пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    oneOf:
                      - type: string
                      - $ref: ../models/getUsers.v1.json
                required:
                  - isError
                  - response
              examples:
                Пользователь добавлен:
                  description: response возвращает поля добавленного пользователя
                  value:
                    isError: false
                    response:
                      - id: 1
                        email: user@user.com
                        permission: user
                Такой пользователь уже есть:
                  value:
                    isError: true
                    response: this user already exists
                Запрос не из под администратора:
                  value:
                    isError: true
                    response: No permission
                Не авторизован:
                  value:
                    isError: true
                    response: Unauthorized
                Поле пароль не отправленно:
                  value:
                    isError: true
                    response: 'ValidationError: password: is a required property'
                Поле пароль слишком короткое:
                  value:
                    isError: true
                    response: 'ValidationError: password: should NOT be shorter than 8 characters'
                Неверный формат email:
                  value:
                    isError: true
                    response: 'ValidationError: email: should match format "email"'
                Данного permission_id нет в базе:
                  value:
                    isError: true
                    response: permission with this id not found
                'permission_id пустое, либо не является числом':
                  value:
                    isError: true
                    response: permission_id must be integer
  /admin/editUser:
    post:
      tags:
        - admin
      summary: Изменение логина и пароля
      operationId: editUser
      description: "Изменение логина(email) и пароля, если пароль пустая строка или пароль не отправлен, аналогично и с логином. \n"
      requestBody:
        description: |
          Отправляем логин и пароль
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer
                email:
                  type: string
                  format: email
                  maximum: 320
                password:
                  type: string
                  minimum: 8
                  maximum: 72
      responses:
        '200':
          description: Возвращает данные отредактированного пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    oneOf:
                      - type: string
                      - $ref: ../models/getUsers.v1.json
              examples:
                Пароль изменен:
                  description: response возвращает поля отредактированного пользователя
                  value:
                    isError: false
                    response:
                      - id: 1
                        email: user@user.com
                        permission: user
                Запрос не из под администратора:
                  value:
                    isError: true
                    response: No permission
                Не авторизован:
                  value:
                    isError: true
                    response: Unauthorized
                Поле пароль не отправленно:
                  value:
                    isError: true
                    response: 'ValidationError: password: is a required property'
                Поле пароль слишком короткое:
                  value:
                    isError: true
                    response: 'ValidationError: password: should NOT be shorter than 8 characters'
                Неверный формат email:
                  value:
                    isError: true
                    response: 'ValidationError: email: should match format "email"'
                Остальные ошибки:
                  value:
                    isError: true
                    response: fail
  /admin/getUsers:
    get:
      tags:
        - admin
      summary: Получить данные всех пользователей
      operationId: getUsers
      description: |
        Получить данные всех пользователей
      responses:
        '200':
          description: В случае успеха передает список пользователей
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                    description: ''
                  response:
                    oneOf:
                      - type: string
                      - $ref: ../models/getUsers.v1.json
                required:
                  - isError
                  - response
              examples: {}
  /admin/getPermission:
    get:
      tags:
        - admin
      summary: Получить данные всех прав
      operationId: getPermission
      description: |
        Получить права и соответствующие им id
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    $ref: ../models/getPermissions.v1.json
                required:
                  - isError
                  - response
              examples:
                Пример:
                  value:
                    isError: false
                    response:
                      - id: 1
                        permission: admin
                      - id: 2
                        permission: moder
                      - id: 3
                        permission: user
  /moder/getPoints:
    get:
      tags:
        - moder
      summary: Получение точек
      operationId: getPoints
      description: |
        Получение точек для модератора, выводятся точки с флагом isModerated=1 из связанной таблицы
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    $ref: ../models/getPointsModer.v1.json
              examples:
                Пример:
                  value:
                    isError: false
                    response:
                      - id: 1224
                        title: Зоомир
                        apartment: null
                        hours: 'Пн-Пт: 8.00-20.00; Сб-Вс: 8.00-19.00'
                        phone: 8-962-763-11-02
                        site: 'https://karmy.su'
                        description: ''
                        full_city_name: 'Майкоп, Республика Адыгея, Россия'
                        house: 524А
                        street: Пионерская улица
                        moder_status: moderated
  /admin/loginAs:
    post:
      summary: Зайти под другим пользователем
      tags:
        - admin
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    type: string
              examples:
                Пример:
                  value:
                    isError: false
                    response: OK
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    type: string
              examples:
                Успех:
                  value:
                    isError: false
                    response: OK
                Нет такого id:
                  value:
                    isError: true
                    response: this userId not found
          description: Ответ
      operationId: get-admin-loginAs
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type:
                    - string
                    - integer
            examples: {}
        description: Отправлем id пользователя под которого мы хотим зайти
      description: 'Заходим под другим пользователем, система будет идентифицировать как другого пользователя до того как не будет выполнен запрос returnToAdmin'
  /admin/returnToAdmin:
    post:
      summary: Вернуться под администратора
      tags:
        - admin
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    type: string
                required:
                  - isError
                  - response
              examples:
                Успех:
                  value:
                    isError: false
                    response: OK
                Неудача:
                  value:
                    isError: true
                    response: fail
      operationId: get-admin-returnToAdmin
      description: 'Работает в связке с loginAs, возвращает права администратора'
  /user/addPoint:
    post:
      summary: Добавление точки в базу данных
      operationId: post-user-addPoint
      responses:
        '200':
          description: 'При успехе вернет данные добавленной точки, при дубликате, данные дубликатов.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  isError:
                    type: boolean
                  response:
                    oneOf:
                      - type: string
                      - $ref: ../models/getPointsUser.v1.json
                      - type: object
                required:
                  - isError
                  - response
              examples:
                Успешно:
                  value:
                    isError: false
                    response:
                      - id: 1223
                        full_city_name: 'Майкоп, Республика Адыгея, Россия'
                        street: улица Карла Маркса
                        house: '23'
                        title: Зоомир
                        lng: 44.6117
                        lat: 40.0888
                        apartment: '77'
                        hours: 'Пн-Пт: 9.00-20.00; Сб-Вс: 8.00-19.00'
                        phone: '656565'
                        site: 'https://karmy.su'
                        isActive: 1
                        description: ''
                        timeStamp: '2020-09-04 17:41:24'
                        moder_status: accept
      tags:
        - user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                lng:
                  type: number
                lat:
                  type: number
                title:
                  type: string
                apartment:
                  type: string
                hours:
                  type: string
                phone:
                  type: string
                site:
                  type: string
                description:
                  type: string
                force:
                  type: boolean
                isActive:
                  type: boolean
              required:
                - lng
                - lat
      description: 'Добавляет точку в базу данных, статус выставляется moder_status выставляется в moderated, для дальнейшего одобрения модератором. Пока статус не выставится в accept точке не будет отображаться на карте. При добавлении точки с похожими координаторами (точка не дальше 200 метров от имеющейся), будет возвращена ошибка. Для того чтоб все равно добавить точку нужно выставить поле force в запросе в true. Все точки подходящие под критерий в базе будут помечены как возможные дубликаты и присвоены к одной группе. В дальнейшем если точка будет близкой хотя бы к одной из группы, как дубликаты будут выданы все точки группы.'
components:
  schemas: {}
